### PR TITLE
Add `generateUndefined` option

### PR DESCRIPTION
**Pull request by risenforces**
In our project, we use GQty without React client - all requests are done on the model-level, and our wrapper above GQty always calls `resolved`. So, it's impossible for us to get `undefined` - the first mapper call is handled by Proxy, and the second has all the requested data.

To remove `undefined` from types, we use our own utility type called `Resolved` (the suggested `CastNotSkeletonDeep` doesn't work well):

```ts
export type NotUndefined<T> = Exclude<T, undefined>;

export type Resolved<T> = T extends any[]
  ? Array<Resolved<T[number]>>
  : T extends (...args: any[]) => any
  ? (...args: Parameters<T>) => Resolved<ReturnType<T>>
  : T extends Record<string, any>
  ? {
      [P in keyof T]-?: Resolved<T[P]>;
    }
  : NotUndefined<T>;
```

It adds extra work for us and heavy computations for TypeScript.

Also, we use `createGqlMapper` abstraction for mappers:

```ts
export const mapMainCourseFields = createGqlMapper<courses>()((course) => {
  return {
    id: course.id,
    image: course.image,
    name: course.title,
    liked: true,
  };
});
```

All this work is needed just to remove `undefined`.

Without `undefined` it can become the following:

```ts
export const mapMainCourseFields = (course: courses) => {
  return {
    id: course.id,
    image: course.image,
    name: course.title,
    liked: true,
  };
};
```

I suggest the `generateUndefined` config option (it's `true` by default). It just allows to remove `undefined` type from `ScalarsEnums` properties. And by the way, it doesn't bring any breaking changes.

### CODE REVIEW

**Review by PabloSzx — CHANGES_REQUESTED** [review]
the `undefined` has a purpose, which is data is just being requested and it's still not there, gqty gives a different purpose for `undefined` from `null`

**Comment by risenforces** [comment]
@PabloSzx this undefined is useful only when React gqty client is used. In my case, there is no React client generated at all. We use `resolved` to fetch data, and we tested that there is no `undefined` at all steps. Initially, it's proxy object (to get the structure for sending graphq request), and then the full data object.

**Comment by PabloSzx** [comment]
well, the proxy object itself returns undefined for every scalar

**Comment by risenforces** [comment]
Ok, it's reasonable, thanks. So, for example, if we try to use `slice` method on scalar string - we will get error in runtime (when mapper is executed on proxy). But it will be ok for the next calls. Luckily, we didn't face this type of issues yet. So, my PR doesn't solve the problem of painful mapper type inference.. I will try to manage this another way. Thanks for your feedback, @PabloSzx!

**Comment by PabloSzx** [comment]
> Ok, it's reasonable, thanks. So, for example, if we try to use `slice` method on scalar string - we will get error in runtime (when mapper is executed on proxy). But it will be ok for the next calls. Luckily, we didn't face this type of issues yet. So, my PR doesn't solve the problem of painful mapper type inference.. I will try to manage this another way. Thanks for your feedback, @PabloSzx!

yep, I understand there is a tradeoff, and there would be a good amount of people that might be able to live with knowing that they can't do `query.helloWorld.toUppercase()` without checking if helloWorld exists when the field is not nullable, but there would also be a lot of people that don't know that, and the types would be lying and typescript would not be able to catch very serious runtime errors. And I prefer type-safety over assuming that the user knows what he's doing.


> we use our own utility type called Resolved (the suggested CastNotSkeletonDeep doesn't work well)

About this, would you mind creating a PR, and within the PR put the situations where the old version breaks? thank you 🙏

**Pull request closed without merging**
