### PR TITLE
docs: create troubleshooting guide

### PR DESCRIPTION
**Pull request by blakewilson**
Create a troubleshooting guide for common "gotchas" in GQty. Currently, this includes:

* React: Each child in a list should have a unique "key" prop skeleton render workaround
* Explanation of data selections behind conditionals and how to avoid this

### CODE REVIEW

**Comment by blakewilson** [comment]
Related #307

**Comment by vicary** [comment]
I think it's a good idea, this provides a place for workarounds of future edge cases.

Forgive me for a few nitpicking,

1. The troubleshooting contents are generally for React, please place it inside the *Usage with React* sub-menu.
2. The skeleton data is a feature (not a bug) to favor [Skeletons](https://mui.com/components/skeleton), and the caveats just feels more intuitive when people just started looking around. Maybe put it back while also add a link from the new troubleshooting page?

**Comment by blakewilson** [comment]
@vicary Thanks for the feedback! Agreed. I'll make these changes.

**Review by vicary — APPROVED** [review]
@blakewilson Looks good, thanks for contributing!

**Pull request merged**
